### ISSUE TITLE
Response 301 Moved Permanently 

### ISSUE THREAD

**Issue by TubYoub** [Kamesuta/BungeePteroPower#10]
Hey, 
I am using you Plugin on a Velocity Server using Spark (i know not the best way to use it but it (works))
Now when i want to start a Server with the Plugin i get this Response:
```
>....[18:33:49 INFO] [BungeePteroPower]: Starting server: hub (Pterodactyl server ID: d162e140)
[18:33:50 WARN] [BungeePteroPower]: Failed to start server: hub. Response code: 301
[18:33:50 INFO] [BungeePteroPower]: Request: https://panel.domain.tld/api/client/servers/d162e140/power POST, Response: 301 <html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>openresty</center>
</body>
</html>
[18:33:50 INFO]: [Ptero] Failed to start server hub
```
(ofc i have the right domain in the config just redaxted for this post)

When i use curl in a console to interact with the API everything works perfectly fine and the server starts
```
curl "https://panel.domain.tld/api/client/servers/d162e140/power" \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer API_Key' \
  -X POST \
  -d '{
  "signal": "start"
}' 
```

I also tried compiling myself and also tried to change the method to use the Pterodactyl API but i always got the same response.

**Comment by Kamesuta** [comment]
## Cause (Speculation)

Upon investigation, it appears that BungeePteroPower is sending start/end signals in `x-www-form-urlencoded format.
[Link to code snippet](https://github.com/Kamesuta/BungeePteroPower/blob/cd9925f/src/main/java/com/kamesuta/bungeepteropower/power/PterodactylController.java#L39-L48)

While my Pterodactyl Panel 1.11.5 starts servers without any issues, it's possible that errors might occur with the version you're using.

The correct API expects application/json, so BungeePteroPower might need to be fixed.
[Link to API documentation](https://api.ptero.sh/#/operations/post-server-power)
[Link to alternative documentation](https://dashflo.net/docs/api/pterodactyl/v1/#req_a23468b60af94a20b57f7a90d1840237)

Could you please try the following?

## Solution Proposal

1. Please verify if the following cURL command succeeds:
    ```sh
    curl "https://panel.domain.tld/api/client/servers/d162e140/power" -H "Content-Type: application/x-www-form-urlencoded" -H "Authorization: Bearer ptlc_YOUR_TOKEN" -X POST -d "signal=start" -i
    ```
    - It sends a request via x-www-form-urlencoded.
    - The `-i` option can output detailed request results.
2. Modify the BungeePteroPower code as shown below and check if it works:
[Link to code snippet (Replace here!)](https://github.com/Kamesuta/BungeePteroPower/blob/cd9925f/src/main/java/com/kamesuta/bungeepteropower/power/PterodactylController.java#L39-L48)
    ```java
            // Create a form body to send power signal
            String jsonBody = "{\"signal\": \"" + signal + "\"}";
    
            // Create a request
            HttpRequest request = HttpRequest.newBuilder()
                    .uri(URI.create(plugin.config.pterodactylUrl.resolve(path).toString()))
                    .header("Content-Type", "application/json")
                    .header("Authorization", "Bearer " + plugin.config.pterodactylApiKey)
                    .POST(HttpRequest.BodyPublishers.ofString(jsonBody))
                    .build();
    ```

## Questions

- What version of Pterodactyl are you using?
  - Are you self-hosting or using a service?
- Are you using Cloudflare Access or similar with Pterodactyl Panel?
  - If yes, have you configured Bypass settings?
  - If configured, please note that behavior might differ between IPv4 and IPv6.
- I'm curious about how you're running the BungeePteroPower Bungeecord plugin on a Velocity Server. Could you provide more details?
  - I searched for a plugin named Spark but found only a [performance profiler named Spark](https://spark.lucko.me/). Could you provide a specific URL?

**Comment by TubYoub** [comment]
## Solution Proposal's
1. I already tried that command and it works perfectly fine and starts the server.
```
HTTP/1.1 204 No Content
Server: openresty
Date: Mon, 04 Mar 2024 09:48:11 GMT
Connection: keep-alive
X-Powered-By: PHP/8.1.24
Cache-Control: no-cache, private
X-RateLimit-Limit: 720
X-RateLimit-Remaining: 719
Access-Control-Allow-Origin:
Access-Control-Allow-Credentials: true
X-Served-By: panel.domain.tld
```
2. Already tried that but i also did that again and it did not work and gave the same response

## Answers
- What version of Pterodactyl are you using?
   - I am Selfhosting Pterodactyl panel and Wings via Docker compose and using the newest release (and yes i have the right DNS Setting in my wings config)
- Are you using Cloudflare Access or similar with Pterodactyl Panel?
   - I am only able to access the Panel Localy and i tunnel it through a reverse proxy (I set it up correcty such as the Pterodactyl docs stated) 
- I'm curious about how you're running the BungeePteroPower Bungeecord plugin on a Velocity Server. Could you provide more details?
   - I am Sorry i don't mean [Spark](https://github.com/lucko/spark) I meant  [Snap](https://github.com/Phoenix616/Snap) (I don't know why but i got it mixed up in my head) 

- And i guess i got a new Plugin to write, a Velocity Plugin. Yay. Fun.

**Comment by TubYoub** [comment]
Okay I am now routing my panel traffic (from BungeePteroPower) through cloudflare tunnel and not locally and it works now. I dont know why, but never change a running system

Edit: But i guess i am gonna do a native Velocity Plugin in the Future

**Comment by Kamesuta** [comment]
> Okay I am now routing my panel traffic (from BungeePteroPower) through cloudflare tunnel and not locally and it works now.

Nice! I'm glad it's resolved.

> I dont know why, but never change a running system

Perhaps there is a problem with the Reverse Proxy.  
If you try to go into the instance where the Velocity server is running and type the curl command, what would be the result?

```sh
# Connect to a machine running Wings with a Velocity server
C:\Users\Kamesuta> ssh panel.domain.tld
# In Wings Server
kamesuta@wings:~$ sudo docker ps
# Copy CONTAINER ID of your Velocity instance and paste it
kamesuta@wings:~$ sudo docker exec <your Velocity instance's CONTAINER ID> -it /bin/sh
# Test the connection to your panel for success!
$ curl "https://panel.domain.tld/api/client/servers/d162e140/power" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer ptlc_YOUR_TOKEN" -X POST -d "{\"signal\":\"start\"}" -i
```

> Edit: But i guess i am gonna do a native Velocity Plugin in the Future

I warmly welcome your willingness to create the Velocity version of BungeePteroPower!  
If you like, please send me a Pull Request!

If you have time, I would like to separate the common code from the Velocity/Bungeecord specific code, like in LuckPerms.  
https://github.com/LuckPerms/LuckPerms/tree/master/velocity

**Comment by TubYoub** [comment]
So we all know we have to set our own DNS or cloudflare is beeing used, but if you create a Server and change the DNS in the wings config afterwards the DNS for the Docker container with the server does not get changed, and wings cant handle my local DNS server even tho every other piece of equipment in my House can use it. 
When i directly use the IP + Port instead of the domain everything works perfectly fine within the docker container, but since your Plugin currently does not support IP's imma have to deal with cloudflare until i make a few changes to this repo right here haha.

Weird behavior from wings right there, imma have to do some investigating in the future, why it does these things.

> If you have time, I would like to separate the common code from the Velocity/Bungeecord specific code, like in LuckPerms

Will do that, I will also add German translation with that but i gotta see when i have time, maybe throuout this week /weekend, next week i dont know yet. 

> If you have time, I would like to separate the common code from the Velocity/Bungeecord specific code, like in LuckPerms.

Will do that in the same Pull Request I guess.

**Comment by Kamesuta** [comment]
> wings cant handle my local DNS server even tho every other piece of equipment in my House can use it.

I did some research and it seems that you can set the DNS for the Docker containers managed by Wings in `config.yml`.
https://github.com/pterodactyl/panel/issues/1965

Just to confirm, did you try to connect using a hostname that can only be used in a LAN environment, like `KAMESUTA-PC.local`?

> When i directly use the IP + Port instead of the domain everything works perfectly fine within the docker container, but since your Plugin currently does not support IP's imma have to deal with cloudflare until i make a few changes to this repo right here haha.

I think you can specify the IP and port like this, can you?

```
# Pterodactyl configuration
pterodactyl:
  # The URL of your pterodactyl panel
  url: "http://192.168.1.123:12345" # Specify IP + Port (Via HTTP)
```

> > If you have time, I would like to separate the common code from the Velocity/Bungeecord specific code, like in LuckPerms.
> 
> Will do that in the same Pull Request I guess.

Thanks!

**Comment by TubYoub** [comment]
> Just to confirm, did you try to connect using a hostname that can only be used in a LAN environment, like KAMESUTA-PC.local?

Yea, my DNS routes every request to my domain locally so i dont have to use different domains locale and outside of it. 
and yea i know about the DNS config and i changed that but got some problems, unkown why.

> I think you can specify the IP and port like this, can you?

Yes works now..... forgot the ```http://``` 

But thanks for the help and imma see when i get to the Plugin :D

**Comment by TubYoub** [comment]
> But thanks for the help and imma see when i get to the Plugin :D

So i dont think i will achieve the same architecture you got so i i will make my own plugin and publish it myself, if you wanna display it as an alternative on your plugin page thanks but i learned now to translate a plugin to another Proxy is not that easy haha.
