### ISSUE TITLE
Port for Velocity 

### ISSUE THREAD

**Issue by TubYoub** [Kamesuta/BungeePteroPower#13]
YOYOYO
Finnaly got the Port ready: [VelocityPteroPower](https://github.com/TubYoub/VelocityPteroPower)
It will be Published on [Modrinth](https://modrinth.com/plugin/velocitypteropower/) (Still under review but will be available soon)
And on [Spigot](https://www.spigotmc.org/resources/velocitypteropower.115931/)

I just blantently ripped of your config, I am sry haha
Best regards

**Comment by Kamesuta** [comment]
Great job!
I will also try to backport the Velocity-compatible part of your code well and see if I can support BungeeCord and Velocity with a common code!
And refer to some implementations that are better than my code!

**Comment by TubYoub** [comment]
Thank you, 
would be nice to have something like that under the same Project.
I also have plans on adding a whitelist (who can auto start a server), and maybe something like a log system.
If you have discord you could hit me up if u like `tubyoub`
