### ISSUE TITLE
AutoJoin doesn't work

### ISSUE THREAD

**Issue by achul123** [Kamesuta/BungeePteroPower#6]
My friend lefraudeur has set up an autojoin system but when testing new versions of the plugin the autojoin system no longer works.

**Comment by Kamesuta** [comment]
Did you update config file?  
`pterodactyl.token` have been changed to `pterodactyl.apiKey`  

Is this only autojoin system? or no longer works on `/ptero start` command?

**Comment by Lefraudeur** [comment]
@Kamesuta fixed this issue by replacing `instanceof ProxiedServer` `instanceof ProxiedPlayer`
45112b8a2f02375581f4a05eb18c6ec49c0a56bc

**Comment by Kamesuta** [comment]
I believe this problem has been fixed.
I'll close this once as resolved.
